baseURL = 'https://jasechen.github.io/resume/'
languageCode = 'zh-tw'
title = 'Resume | Jase Chen'

theme = "devresume"
#googleAnalytics = "UA-XXXXXXX-Y"


[params]
enable = true
author = "Jase Chen"
description = "Jase's Resume"

primaryColor = "#54B689"
textPrimaryColor = "#292929"


[params.profile]
enable = true
name = "陳璽元"
nickname = "JaseChen"
tagline = "Senior Backend Engineer"
avatar = "avatar.png"


[params.contact]
enable = true
location = "Taipei, Taiwan"

#[[params.contact.list]]
#icon = "fas fa-phone-square"
#url  = "tel:#"
#text = "+886 952 969 228"
#title = "+886 952 969 228"

[[params.contact.list]]
icon  = "fas fa-envelope-square"
url   = "mailto:jase.chen@gmail.com"
text  = "jase.chen@gmail.com"
title = "jase.chen@gmail.com"

[[params.contact.list]]
icon  = "fas fa-globe"
url   = "https://jctalk.today"
text  = "jctalk.today"
title = "jctalk.today"


[params.skills]
enable = true

[[params.skills.list]]
title = "Operation System"
[[params.skills.list.items]]
details = "Linux"
[[params.skills.list.items]]
details = "BSD"
[[params.skills.list.items]]
details = "MacOS"
[[params.skills.list.items]]
details = "Windows-Family"

[[params.skills.list]]
title = "Database"
[[params.skills.list.items]]
details = "MySQL"


[params.education]
enable = true

[[params.education.list]]
icon = "fas fa-globe"
degree = "BSc in Information Management"
university = "Yuan Ze University"
dates = "1996 - 2000"


[params.awards]
enable = false

[[params.awards.list]]
name = "Award Lorem Ipsum"
body = "Microsoft lorem ipsum"
date = "2019"


[params.languages]
enable = true

[[params.languages.list]]
name = "Mandarin Chinese"
level = "Native"


[params.interests]
enable = false

[[params.interests.list]]
name = "Climbing"
[[params.interests.list]]
name = "Snowboarding"
[[params.interests.list]]
name = "Photography"
[[params.interests.list]]
name = "Travelling"


[params.summary]
enable = true
text = "超過10年 Linux、Apache、PHP 及 MySQL 環境的開發經驗。曾任 Groupon (地圖日記) 資深軟體工程師及多家公司開發部經理、資深程式設計師，負責網站、專案開發及系統建置，並有管理 2-5 人小組經驗。注重專案開發流程控管及小組成員間的溝通合作，近年工作內容朝專案管理、雲端系統管理及 PHP Backend API 開發為主。"


[params.experience]
enable = true

[[params.experience.list]]
title = "Senior Software Engineer"
dates = "2019 - Present"
company = "Google"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
[[params.experience.list.items]]
details = "Lorem ipsum dolor sit amet, consectetuer."
[[params.experience.list.items]]
details = "Aenean commodo ligula eget dolor."
[[params.experience.list.items]]
details = "Etiam ultricies nisi vel augue."

[[params.experience.list]]
title = "Lead Software Developer"
dates = "2016 - 2019"
company = "Apple"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
[[params.experience.list.items]]
details = "Lorem ipsum dolor sit amet, consectetuer."
[[params.experience.list.items]]
details = "Aenean commodo ligula eget dolor."

[[params.experience.list]]
title = "Senior Software Developer"
dates = "2014 - 2016"
company = "Dropbox"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

[[params.experience.list]]
title = "Senior Developer"
dates = "2013 - 2014"
company = "Uber"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

[[params.experience.list]]
title = "Backend Developer"
dates = "2014 - 2016"
company = "Amazon"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

[[params.experience.list]]
title = "Frontend Developer"
dates = "2013 - 2014"
company = "Startup"
details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."



[params.projects]
enable = true

[[params.projects.list]]
title = "Project Lorem Ipsum"
meta = "Open Source"
tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

[[params.projects.list]]
title = "Project Sed Fringilla"
meta = "Open Source"
tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

[[params.projects.list]]
title = "Project Praesent"
meta = "Open Source"
tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."



[params.information]
enable = true

[[params.information.list]]
title = "Papers"
[[params.information.list.items]]
details = "2018 · Lorem Ipsum"
[[params.information.list.items]]
details = "2016 · Sed Fringilla"

[[params.information.list]]
title = "Interests"
details = "Climbing, Snowboarding, Photography, Travelling"


[params.social]
enable = false

[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/jasechen"
title = "jasechen"
[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/jasechen"
title = "jasechen"
[[params.social.list]]
icon = "fab fa-twitter-square"
url = "//twitter.com/jasechen"
title = "@jasechen"


[params.footer]
    copyright = ""